name: tracy-profiler
version: 0.1.1.0
github: "haskell-game/tracy-profiler"
license: BSD-3-Clause
author: "IC Rainbow"
maintainer: "aenor.realm@gmail.com"
copyright: "2025 IC Rainbow"

extra-doc-files:
- README.md
- CHANGELOG.md
- readme.png

category: Profiling
synopsis: Haskell bindings for Tracy frame profiler
# description: |
#   <https://github.com/wolfpld/tracy>

dependencies:
- base >= 4.16 && < 5
- unliftio-core

flags:
  enable:
    description:
      Enable to actually call the Tracy functions and produce data.
      Otherwise the wrappers will be no-ops.
    manual: true
    default: false
  on_demand:
    description:
      Don't generate and keep events if there's no connection.
      Enable if your libtracyclient has this enabled.
    manual: true
    default: false
  manual_lifetime:
    description:
      Manually manage profiler lifetime.
      Enable if your libtracyclient has this enabled.
    manual: true
    default: false
  fibers:
    description:
      Enable if your libtracyclient has this enabled.
    manual: true
    default: false
  has_callstack:
    description:
      Enable if your libtracyclient has this enabled.
    manual: true
    default: false
  zones_pedantic:
    description:
      Crash when a zone is starting on an unbound thread.
    manual: true
    default: true
  zones_unsafe:
    description:
      Skip the bound-thread check for zones.
      This may crash the profile server with "zone ended twice" error.
    manual: true
    default: false

library:
  source-dirs: src
  when:
  - condition: flag(enable)
    cpp-options:
    - -DTRACY_ENABLE
    extra-libraries:
    - TracyClient
    - stdc++
  - condition: flag(manual_lifetime)
    cpp-options:
    - -DTRACY_MANUAL_LIFETIME
  - condition: flag(on_demand)
    cpp-options:
    - -DTRACY_ON_DEMAND
  - condition: flag(fibers)
    cpp-options:
    - -DTRACY_FIBERS
  - condition: flag(has_callstack)
    cpp-options:
    - -DTRACY_HAS_CALLSTACK
  - condition: flag(zones_pedantic)
    cpp-options:
    - -DZONES_PEDANTIC
  - condition: flag(zones_unsafe)
    cpp-options:
    - -DZONES_UNSAFE

  dependencies:
  - bytestring
  - text >= 2.0 && <3
  - webcolor-labels

tests:
  tracy-profiler-test:
    main: Readme.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tracy-profiler
    - random
    - text

language: GHC2021

default-extensions:
- BlockArguments
- DerivingStrategies
- DuplicateRecordFields
- ImportQualifiedPost
- LambdaCase
- NoFieldSelectors
- OverloadedLabels
- OverloadedStrings
- RecordWildCards
- StrictData
- ImplicitParams

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
